wandb_version: 1

seed:
  desc: null
  value: 42
input_size:
  desc: null
  value: 1
hidden_sizes:
  desc: null
  value:
  - 5
  - 5
output_size:
  desc: null
  value: 1
initial_activation_list:
  desc: null
  value:
  - jax._src.nn.functions.relu
n_samples:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 0.01
num_epochs:
  desc: null
  value: 1000
add_node_every:
  desc: null
  value: 50
threshold:
  desc: null
  value: 0.0009
activation_list:
  desc: null
  value:
  - jax._src.nn.functions.relu
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716893424
    t:
      1:
      - 12
      - 55
      2:
      - 12
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.3
      5: 0.17.0
      8:
      - 1
      - 5
      13: linux-x86_64
