# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NeuralNetworkEvolution',
                'doc_host': 'https://ParticularlyPythonicBS.github.io',
                'git_url': 'https://github.com/ParticularlyPythonicBS/NeuralNetworkEvolution',
                'lib_path': 'NeuralNetworkEvolution'},
  'syms': {'NeuralNetworkEvolution.core': {'NeuralNetworkEvolution.core.foo': ('core.html#foo', 'NeuralNetworkEvolution/core.py')}}}
