# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_activations.ipynb.

# %% auto 0
__all__ = ['identity', 'sin']

# %% ../nbs/02_activations.ipynb 3
import jax.numpy as jnp

# %% ../nbs/02_activations.ipynb 4
def identity(x):
    """
    Identity activation function
    """
    return x

# %% ../nbs/02_activations.ipynb 5
def sin(x):
    """
    Sine activation function
    """
    return jnp.sin(x)
