# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_MLP.ipynb.

# %% auto 0
__all__ = ['identity']

# %% ../nbs/03_MLP.ipynb 3
import jax
import jax.numpy as jnp
import equinox as eqx

from .neuron import Neuron

# %% ../nbs/03_MLP.ipynb 4
def identity(x):
    """
    Identity activation function
    """
    return x
